name: Test the full analyze and test workflow

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  analyze-test:
    uses: weewx-extensions/development_tools/.github/workflows/full-analyze-test.yml@v4
    with:
      module-name: 'nofify'
      #pip-list: 'paho-mqtt'
      #package-list: 'mosquitto'
      function-test: false
      integration-test: false
      e2e-test: false
      #flake-extra-parms: '--exclude tests'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}